[tool.poetry]
name = "pythol-2"
version = "0.1.0"
description = "sugon deez"
authors = ["joemama@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ursina = "^4.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
